<wsdl:definitions
     name="DBPolling"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBPolling/DBPolling"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBPolling/DBPolling"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBPolling"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DBPolling_plt" >
    <plt:role name="DBPolling_role" >
      <plt:portType name="tns:DBPolling_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBPolling" schemaLocation="../Schemas/DBPolling_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpinfoCollection_msg">
        <wsdl:part name="EmpinfoCollection" element="top:EmpinfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBPolling_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EmpinfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
