<wsdl:definitions
     name="DBDelete"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBDeleteProj/DBDelete"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBDeleteProj/DBDelete"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBDelete"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DBDelete_plt" >
    <plt:role name="DBDelete_role" >
      <plt:portType name="tns:DBDelete_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBDelete" schemaLocation="../Schemas/DBDelete_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpinfoCollection_msg">
        <wsdl:part name="EmpinfoCollection" element="top:EmpinfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBDelete_ptt">
        <wsdl:operation name="delete">
            <wsdl:input message="tns:EmpinfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
