<wsdl:definitions
     name="DBInsertDatsa"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBDatainsertData/DBInsertDatsa"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Batch8/DBDatainsertData/DBInsertDatsa"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBInsertDatsa"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DBInsertDatsa_plt" >
    <plt:role name="DBInsertDatsa_role" >
      <plt:portType name="tns:DBInsertDatsa_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBInsertDatsa" schemaLocation="../Schemas/DBInsertDatsa_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpinfoCollection_msg">
        <wsdl:part name="EmpinfoCollection" element="top:EmpinfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBInsertDatsa_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EmpinfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
